### PR TITLE
Use post-command-hook to trigger flyspell

### LINKED ISSUE #34: Redundant aspell processes after magit-commit
Emacs -Q:
```elisp
(progn
  (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                           ("nongnu" . "https://elpa.nongnu.org/nongnu/")))
  (package-install 'magit)
  (package-install 'guess-language)
  (package-activate-all)

  (setq guess-language-languages '(en sl))
  (setq-default ispell-dictionary "slovenian")
  (add-hook 'text-mode-hook 'flyspell-mode)
  (add-hook 'flyspell-mode-hook 'guess-language-mode))
```

Each `M-x magit-commit-create` will leave an extra aspell process.
(A bit more info can be found on
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=48379 )

### PR DESCRIPTION
**Pull request by jakanakaevangeli**
Fixes https://github.com/tmalsburg/guess-language.el/issues/34.

I improved a little on the patch proposed in the issue.
After testing for a week, I didn't encounter any problems so I went ahead and
made a PR.

Committed under my real name as I have FSF copyright paperwork signed.

### CODE REVIEW

**Comment by tmalsburg** [comment]
Thank you! I will hopefully find time to look into this next week.  (Currently preparing for our move on the weekend.)

**Comment by jakanakaevangeli** [comment]
Ping.
(Sorry to bother, personal reasons, I want to update and restart my
Emacs soon as I am running out of RAM.)

**Comment by tmalsburg** [comment]
Sorry for taking so long. Merged.  Hope this works.  We've tried a couple of things already and this seems to be surprisingly tricky.

**Comment by jakanakaevangeli** [comment]
Thanks!

**Pull request merged**
